name: local_game
description: "A word game for Shona and Ndebele"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  go_router: ^16.1.0
  shared_preferences: ^2.2.3
  freezed_annotation: ^2.4.1
  
  get_it: ^8.2.0
  injectable: ^2.5.1
  sqflite: ^2.3.3+1
  path_provider: ^2.1.3
  intl: ^0.20.2
  lottie: ^3.3.1
  audioplayers: ^6.5.0
  flutter_svg: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  freezed: ^2.5.2
  injectable_generator: ^2.6.1
  mockito: ^5.4.4
  sqflite_common_ffi: ^2.3.3

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/data/sql/schema_v1.sql
    - assets/animations/
    - assets/sounds/
    - assets/images/
    - assets/resources/
    - assets/fonts/
    - assets/svg/

  fonts:
    - family: Handlee
      fonts:
        - asset: assets/fonts/Handlee-Regular.ttf
  